# Generated by Django 3.1.13 on 2021-08-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerServiceSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=12)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('problem_desciption', models.TextField()),
                ('date_time_callback', models.DateTimeField()),
                ('comment', models.TextField()),
                ('arhived', models.BooleanField(default=False)),
            ],
        ),
    ]
