# Generated by Django 2.2.6 on 2021-08-15 15:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service_supports', '0002_auto_20210815_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerservicesupport',
            name='submited_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
