# Generated by Django 2.2.6 on 2021-08-17 07:22

import customer_service_supports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service_supports', '0004_auto_20210816_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerservicesupport',
            name='date_time_callback',
            field=models.DateTimeField(blank=True, null=True, validators=[customer_service_supports.models.validateDateTime]),
        ),
    ]
